### ISSUE TITLE
🐛 BUG: icons are black in dark mode

### ISSUE THREAD

**Issue by jaowork** [dailydotdev/daily#1842]
### What went wrong? 🤔

it's hard to see the icons in dark mode. they are all black

![Image](https://github.com/user-attachments/assets/ae6c78e1-a937-4b19-ab88-6d62c463dc4b)

### Expected Behavior

visible icons

### Steps to Reproduce Issue

```bash
see screenshot
```

### Solution Proposed

visible icons

### Screenshots

![Image](https://github.com/user-attachments/assets/8ff69161-b1e9-43bb-8690-10060c74f7be)

![Image](https://github.com/user-attachments/assets/9079a677-36f4-49ff-aaf4-b14de3ace2e2)

### Browsers

Firefox

### OS

Mac

### Additional Context

```bash

```

### Code of Conduct

- [x] I follow the conditions of this project.

**Comment by actuallysherlock** [comment]
This issue has been fixed, they should close it.

**Comment by omBratteng** [comment]
Think it was just a local cache issue, and as @actuallysherlock, swapping between light and dark would probably fix it

**Comment by jaowork** [comment]
> The issue is fixed (I think). You should close this thread. If you are still experiencing it, I would recommend you to switch to light mode and then back to dark mode.
> 
> ![Image](https://github.com/user-attachments/assets/5a914a57-4341-4f5b-9d0d-df71e2a7d9e6)

It is still not working for me. Switching light to dark doesn't fix it either

**Comment by jaoord** [comment]
I have also cleared all site data to no avail

**Comment by omBratteng** [comment]
Don't think we have any `mac-text-color` variables, are you using any extensions that might mess with the CSS?

**Comment by jaowork** [comment]
It is indeed coming from my theme (chrome://browser/skin/userChrome.css)
Weird that a variable defined in a browser skin (--button-color: var(--mac-text-color) !important;) can leak through all the way to the final rendering of a website. 

It is fixed now by disabling waterfox theme customizations

**Comment by actuallysherlock** [comment]
I don't have any experience with Firefox specifically. What I do know is that the CSS for any extension is also rendered on Chrome. I think the same would have happened on Firefox, the styles (and variables) for the theme could have loaded after and interfered with the CSS for daily.dev (as I assume both are defined inside :root), thus overwriting the variable based on specificity and the order.
