### ISSUE TITLE
🐛 BUG: When opening the extension and clicking on the purple button, nothing happens.

### ISSUE THREAD

**Issue by SonnyAD** [dailydotdev/daily#574]
### What went wrong? 🤔

When opening the extension and clicking on the purple button, nothing happens.

### Expected Behavior

A popup should appear.

### Actual Behavior

Nothing happens. 

### Steps to Reproduce Issue

Open the extension and click on the purple button on the top right.

### Solution

NA

#### Operating System

Windows 11

#### Version of Daily

3.16.1

#### Browser

Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by sshanzel** [comment]
Hi @SonnyAD, thanks for reporting. Does this happen consistently?

**Comment by SonnyAD** [comment]
Yeah, I have never seen the expected popup. Screen recording and console, sure will do.

**Comment by SonnyAD** [comment]
Nothing in the console.

https://user-images.githubusercontent.com/10231464/172983914-7bd108fb-f7e6-47dd-8cf9-8bd88b498151.mp4

**Comment by sshanzel** [comment]
> Nothing in the console.

Thank you so much for the additional info. Do you have any other devices? Does it happen on those ones as well?

**Comment by SonnyAD** [comment]
I tried with another browser (Firefox) and same behavior.

**Comment by sshanzel** [comment]
> I tried with another browser (Firefox) and same behavior.

Wow. Thank you for the confirmation. One last thing, in the actual post page where people comment, if you hover on anyone's profile picture, does it display anything?

**Comment by sshanzel** [comment]
I see. Looks like the issue in your case is app wide. Can you please try the hover I mentioned while using incognito? Also, do you have any sort of add-ons or anything unique in your setup? I am trying to reproduce the case and wanted the environment to be as much the same as you. Thank you for your patience! 🚢

**Comment by SonnyAD** [comment]
Well, it's more than app wide, because I have the same behavior in Chrome and Firefox.  
I also tried incognito and same. 

In Firefox, I have zero extensions aside daily dev extension itself.

**Comment by sshanzel** [comment]
> Well, it's more than app wide, because I have the same behavior in Chrome and Firefox.

I totally agree, that's why I think there is something unique with your setup as I am not able to reproduce the issue.

**Comment by rebelchris** [comment]
@SonnyAD We deployed a fix that hopefully addresses this issue as well.
Would you be so kind to re-test if?

Closing the issue for now.

**Comment by SonnyAD** [comment]
Hi @sshanzel I tried on both Chrome and Firefox and still the same problem. 

Some more info about my computer if that can help. 

![image](https://user-images.githubusercontent.com/10231464/177905510-c90360df-c560-4ac0-af6d-85fa54ac5bd8.png)

Using Windows 11. My screen is 4K, and you can see the scale I use.
