### ISSUE TITLE
Bug: Duplicate articles

### ISSUE THREAD

**Issue by TheCrazyMax** [dailydotdev/daily#97]
#### Bug Report

Explanation: I was not able to find when it happens, but I have all the sources checked and I sometimes have duplicate articles in the list. When I bookmark one, the duplicate is bookmarked, not the one I click on.

Reproduce: I didn't find how to reproduce

Version: 2.6.0

Browser version: 77.0.3865.90 (Official Build) (64-bit) (cohort: Stable)

OS: Windows 10 OS Version 1903 (Build 18362.356)

![image](https://user-images.githubusercontent.com/15264289/65576234-da671d00-df71-11e9-8327-d6f8ce8873e8.png)

**Comment by tsahimatsliah** [comment]
Hi Maxime

We are sorry you had such an experience, and we appreciate the time and effort you put into writing this bug. 

I tried to find how it happened to you with no success, and I want to help you and fix that bug. 

Could you try to give me more details about your bug or maybe send me a video?

**Comment by TheCrazyMax** [comment]
Hello @tsahimatsliah ,
Ok, no problem. I'll record it whenever it happens to me again. There is no particular scenario for this to happen. I just opened a new tab and scrolled through the list (a bit more than usual) and saw a duplicate article.

**Comment by TheCrazyMax** [comment]
Hello,
This issue is still happening from time to time and I can see that it's always at position 31 & 32 on the grid. Also, the article on the left is from 8 hours ago and the one just after is from 9 hours ago. So I guess it can be due to an update on the article that is considering it as new
![image](https://user-images.githubusercontent.com/15264289/67365395-e09ce900-f571-11e9-9d5a-78b422b3a76a.png)

I hope it will help you to look into the issue. I was not able to record it as I don't know in advance when it will happen.

**Comment by idoshamun** [comment]
I think you might be right and if not I have another guess, maybe something to do with the pagination mechanism. I'll check it out :)

**Comment by TheCrazyMax** [comment]
Hello @idoshamun, 
I don't know where you are on that issue, but I just got it again and finally thought about recording it.
https://www.loom.com/share/1f012c69f5da4ea39ff6c05380b0dcde
I hope it will help you

**Comment by idoshamun** [comment]
Thanks for sharing the video, I will create a workaround in the meantime to fix this issue until I find the root cause.

**Comment by TheCrazyMax** [comment]
Ok thank you, no problem :)

**Comment by idoshamun** [comment]
Hopefully, I fixed it in v2.14.4.
Should be released soon.

**Comment by ccremer** [comment]
Unfortunately, this is still an issue today
![image](https://github.com/dailydotdev/daily/assets/12159026/22b67613-6d3d-4c7c-b79d-1223b15bc067)

Can we get this reopened or should I open a new issue?

**Comment by idoshamun** [comment]
It should be fixed now :)
